name: SDK CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!release-*'
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
