name: SDK publish

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  publish:
    runs-on: macos-13
    steps:
    - name: Remove from Cocoapods
      run: |
        set -eo pipefail
        pod trunk delete Mindbox 2.6.2
        pod trunk delete MindboxNotifications 2.6.2
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
