name: SDK publish

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
    - name: Run unit tests
      run: bundle exec fastlane unitTestLane
      
  publish:
    needs: [unit]
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Release generation
      run: ./git-release.sh "${{ github.event.head_commit.message }}" "${{secrets.GITHUBACCESSTOKEN}}" "${{secrets.GITHUBUSER}}"
    - name: Update bundler
      run: gem install bundler
    - name: Install bundler dependencies
      run: bundle install
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app
    - name: Run build
      run: bundle exec fastlane buildLane
      env:
        CI: true
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push MindboxLogger.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
